#
# Dockerfile for wally builds on Debian trixie (stable).
# build from this directory with e.g:
#     DOCKER_BUILDKIT=1 docker build . -t blockstream/wallycore -f Dockerfile_trixie
# and for linux/arm64:
#     DOCKER_BUILDKIT=1 docker build . -t blockstream/wallycore -f Dockerfile_trixie --platform linux/arm64 --build-arg TARGETARCH=arm64
#
FROM debian:trixie-slim@sha256:a99cfc517144bc59b1978475ec53b46ecabec7e43635402ee5b77cc54cd1b20a
WORKDIR /root
COPY trixie_deps.sh ./deps.sh
COPY requirements.txt ./contrib/requirements.txt
ARG TARGETARCH=amd64
ENV TARGETARCH=${TARGETARCH}
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-${TARGETARCH}
RUN ./deps.sh && rm ./deps.sh
ENV ANDROID_NDK=/opt/android-ndk-r26b
